---
- hosts: ai-api-testing
  become: yes
  vars:
    pip_install_packages:
      - name: docker
    caddy_config: |
      apitest.ai.acmucsd.com {
        reverse_proxy 127.0.0.1:9000
      }
    caddy_setcap: true
    caddy_systemd_capabilities_enabled: false
    caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
  roles:
    - common
    - geerlingguy.pip
    - geerlingguy.docker
    - role: ai-api
      testing: true
    - caddy_ansible.caddy_ansible
