---
- hosts: bot
  become: yes
  roles:
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
        - "origin=Ubuntu,archive=${distro_codename}-security"
        - "o=Ubuntu,a=${distro_codename}"
        - "o=Ubuntu,a=${distro_codename}-updates"
        - "o=Ubuntu,a=${distro_codename}-proposed-updates"
      unattended_package_blacklist: [nodejs, vim]
    - geerlingguy.nodejs
    - breadbot
