---
- hosts: mc
  become: yes
  vars:
    caddy_config: |
      mc.acmucsd.com {
        root * /opt/minecraft/map
        file_server
      }

  roles:
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
        - "origin=Ubuntu,archive=${distro_codename}-security"
        - "o=Ubuntu,a=${distro_codename}"
        - "o=Ubuntu,a=${distro_codename}-updates"
        - "o=Ubuntu,a=${distro_codename}-proposed-updates"
      unattended_package_blacklist: [caddy, vim, minecraft-overviewer]
    - geerlingguy.java
    - minecraft-overviewer
    - borgbackup
    - mc
    - caddy_ansible.caddy_ansible
