---
- hosts: monitor
  become: yes
  vars:
    caddy_config: |
      monitor.acmucsd.com {
        reverse_proxy 127.0.0.1:3000
      }
    caddy_setcap: true
    caddy_systemd_capabilities_enabled: true
    caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
    prometheus_targets:
      node:
        targets:
          - "localhost:9100"
          - "bot.acmucsd.com:9100"
          - "pass.acmucsd.com:9100"
          - "acmurl.com:9100"
          - "api.ai.acmucsd.com:9100"
          - "apitest.ai.acmucsd.com:9100"
  roles:
    - geerlingguy.node_exporter
    - cloudalchemy.prometheus
    - atosatto.grafana
    - caddy_ansible.caddy_ansible
