#+TITLE: ACM Tech Stack
#+DESCRIPTION: Moving all of ACM's services to cloud providers is going to be a tough one.

This repository includes all the files necessary to describe and deploy the
technology stack of ACM @ UCSD. You will find files such as:

- Ansible roles and playbooks
- Terraform files
- Custom patches and images for certain services

* Introduction

ACM @ UCSD's previous tech stack was split across multiple providers; GCP,
Heroku, Netlify, etc. Consolidation of most of the provided services onto
self-controlled cloud services would be beneficial for billing purposes. This
document lists the steps taken to migrate most of the tech stack to Azure and AWS.

This document will be included as part of the =tech-stack= repository, so you may
read on the process at your leisure.

Deployment and provisioning of instances supported by Ansible and Terraform.

* Migration Plan
The previous tech stack had the following main services:
- Membership Portal UI & API
- ACM Live
- Minecraft Server
- BreadBot
- Password Manager

Services will be deployed on separate instances of reasonable size for
each one.

We will begin by provisioning instances for each service.

