---
collections:
  - name: community.general
roles:
  - name: geerlingguy.pip
  - name: geerlingguy.docker
  - name: geerlingguy.nodejs
  - name: geerlingguy.java
  - name: caddy_ansible.caddy_ansible
  - name: jnv.unattended-upgrades
  - name: atosatto.grafana
  - name: cloudalchemy.prometheus
  - name: geerlingguy.node_exporter
