---
- name: "Ensure user for BreadBot exists."
  user:
    name: bot
    comment: BreadBot Account
- name: "Install dependencies to build Node modules for BreadBot."
  apt:
    pkg:
      - g++
      - gcc
      - make
    state: latest
- name: "Get latest version of the BreadBot Git repo"
  git:
    repo: "https://github.com/acmucsd/discord-bot"
    dest: /opt/discord-bot
- name: "Upload envfile for BreadBot."
  copy:
    src: "{{ role_path }}/files/.env"
    dest: /opt/discord-bot/
    owner: bot
    group: bot
- name: "Install npm dependencies for BreadBot."
  command: npm install
  become: yes
  args:
    chdir: /opt/discord-bot
- name: "Fix permissions for BreadBot repo."
  file:
    path: /opt/discord-bot/
    owner: bot
    group: bot
    recurse: yes
- name: "Upload service file for BreadBot."
  copy:
    src: "{{ role_path }}/files/breadbot.service"
    dest: /etc/systemd/system/
    owner: root
    group: root
- name: "Refresh daemon for Systemd."
  systemd:
    daemon_reload: yes
- name: "Ensure BreadBot service is started."
  systemd:
    name: breadbot
    state: restarted
    enabled: yes
