---
- name: "Ensure user for password manager exists."
  user:
    name: pass
    comment: Password Manager Account
    group: docker
- name: "Ensure Docker configuration and envfiles exist."
  copy:
    src: "{{ role_path }}/files/"
    dest: "/home/pass/"
    owner: pass
    group: docker
    mode: "0644"
- name: "Ensure folder for bitwarden_rs to store internal data exists."
  file:
    path: "/home/pass/bw-data"
    state: directory
    owner: pass
    group: docker
    mode: "0755"
- name: "Add service unit file for Password Manager to Systemd."
  copy:
    remote_src: yes
    src: "/home/pass/pass.service"
    dest: "/etc/systemd/system"
    owner: root
    group: root
- name: "Refresh daemon for Systemd."
  systemd:
    daemon_reload: yes
- name: "Ensure Password Manager service is started."
  systemd:
    name: pass
    state: started
